defmodule Zippiker.Repo.Migrations.AddUserTeamsRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :current_team, :text
    end

    alter table(:teams) do
      add :owner_user_id,
          references(:users,
            column: :id,
            name: "teams_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:teams, "teams_owner_user_id_fkey")

    alter table(:teams) do
      remove :owner_user_id
    end

    alter table(:users) do
      remove :current_team
    end
  end
end
